on: push

name: Build

jobs:
  windows:
    name: Windows x86_64
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Prepare dependencies
        run: git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build
        run: |
          $DepsPath = $(get-location).Path + '/xmrig-deps/msvc2019/x64';
          $DepsPath = $DepsPath.replace('\','/');
          mkdir build && cd build
          dir $CurrentDir
          cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS="$DepsPath"
          cmake --build . --config Release
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/Release