on: push

name: Build

jobs:
  windows:
    name: Windows x86_64
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Prepare dependencies
        run: git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=../xmrig-deps/msvc2019/x64
          cmake --build . --config Release