on: push

name: Test builds

jobs:
  build_win:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies and build project
        run: |
          npm install  
          npm run build  


  build_lin:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Linux tools
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies and build project
        run: |
          npm install 
          npm run build  
          
  build_mac:
    name: macOS build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies and build project
        run: |
          npm install  
          npm run build  
         
