on: push

name: Test builds

jobs:
  build_win:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'  
      - name: Checkout deps
        run: git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build project on Windows
        run: |
          cmake . -G "MinGW Makefiles" -DXMRIG_DEPS=xmrig-deps\gcc\x64
          make -j2

  build_lin:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Linux tools
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16' 
      - name: Build project on Linux
        run: |
          cmake .
          make -j$(nproc)

  build_mac:
    name: macOS build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Checkout deps
        run: git clone https://github.com/xmrig/xmrig-deps.git
      - name: Install HWLOC on macOS
        run: brew install hwloc
      - name: Build project on macOS
        run: |
          cmake .
          make -j$(sysctl -n hw.logicalcpu)
